---
# Automation of Lights
#
alias: 'Rule 1 Lights on in the evening'
# Lights on 30 minutes before sunset
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
action:
  service: homeassistant.turn_on
  entity_id: group.all_lights
