language: python
python:
- '3.6'
before_install:
- cp secrets_dummy.yaml secrets.yaml
- touch home-assistant_v2.db
- touch home-assistant.log
- sudo apt-get install -y libudev-dev
install:
- pip3 install homeassistant
script:
- hass --script check_config -c . -f
notifications:
  slack: agdonassociates:M26rargX76TeQ5gyK0iadxoe
