- id: '1661425963315'
  alias: Extend HW by 1 hour
  description: Sets the hot water thermostat to 26C for a period of 60 mins so that
    bathroom towel rail gets hot.
  trigger:
  - platform: state
    entity_id:
    - input_button.extend_hw
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 34
    target:
      entity_id: climate.hot_water
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: climate.set_temperature
    data:
      temperature: 0
    target:
      entity_id: climate.hot_water
  mode: restart
- id: '1661427731373'
  alias: Extend CH by 1 hour
  description: Extends the time at which the CH goes to night mode.
  trigger:
  - platform: state
    entity_id:
    - input_button.extend_ch
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.ch_extended
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.ch_extended
  mode: restart
