- id: '1661425963315'
  alias: Extend HW by 1 hour
  description: Sets the hot water thermostat to 26C for a period of 60 mins so that
    bathroom towel rail gets hot.
  trigger:
  - platform: state
    entity_id:
    - input_button.extend_hw
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 34
    target:
      entity_id: climate.hot_water
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: climate.set_temperature
    data:
      temperature: 0
    target:
      entity_id: climate.hot_water
  mode: restart
- id: '1661427731373'
  alias: Extend CH by 1 hour
  description: Extends the time at which the CH goes to night mode.
  trigger:
  - platform: state
    entity_id:
    - input_button.extend_ch
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.ch_extended
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.ch_extended
  mode: restart
- id: '1667506703025'
  alias: Shack light on after motion when dark
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.shack_occupied
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ state_attr(''sun.sun'', ''elevation'') < 4 }}'
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.shack_light
- id: '1667735322575'
  alias: Shack lights off when empty
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.shack_occupied
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.shack_light
  mode: single
- id: '1667735322576'
  alias: Lights on at sunset
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sunset
    from: 'off'
    to: 'on'
  action:
  - service: scene.turn_on
    entity_id: scene.evening
- id: '1667735322577'
  alias: lights_out
  trigger:
    platform: time
    at: '23:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.goodnight
- id: '1667735322578'
  alias: Rainy Day
  trigger:
    platform: state
    entity_id: sensor.dark_sky_precip_intensity
    to: rain
  condition:
  - condition: state
    entity_id: device_tracker.ghip7plus
    state: home
  - condition: time
    after: '14:00'
    before: '23:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening
- id: '1670157209661'
  alias: Christmas Lights On
  description: Turn on Christmas Lights id dusk and enabled
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sunset
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.christmas
    state: 'on'
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.christmas_lights
  mode: single
- id: '1671291723470'
  alias: Reset bedtime overides
  description: Periodically overnight, reset the booleans that get set when we go
    to bed.
  trigger:
  - platform: time
    at: 00:01:00
  - platform: time
    at: 01:00:00
  - platform: time
    at: 02:00:00
  - platform: time
    at: 03:00:00
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id:
      - input_boolean.central_heating_manual
      - input_boolean.simulate_bedtime
      - input_boolean.ch_extended
  mode: single
- id: '1671296065126'
  alias: switch on central heating
  description: switch on the boiler when a room needs heat
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.we_need_heat
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.central_heating_boiler_ch
  mode: single
- id: '1671296746796'
  alias: Control CH boiler
  description: Control CH boiler based on state of "We need heat" input_boolean
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.we_need_heat
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.central_heating_boiler_ch
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.we_need_heat
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.central_heating_boiler_ch
  mode: single
- id: '1671785551975'
  alias: sunset
  description: Turn on input_boolean.sunset when the sun sets
  trigger:
  - platform: sun
    event: sunset
    offset: '- 00:30:00'
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sunset
  - condition: state
    entity_id: sun.sun
    state: above_horizon
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sunset
  mode: single
- id: '1690796324661'
  alias: Weekly reboot
  description: ''
  use_blueprint:
    path: Chef-de-IT/Reboot-HA-weekly.yaml
- id: '1692366440304'
  alias: Alert when home assistant (re)starts
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.pushover
    data:
      message: Home assistant has (re)started
      title: Home Assistant
  mode: single
- id: '1694423107170'
  alias: _Temp Switch on Xmas lihts
  description: Because the goodnight automation is turning off the feed to m5kvk-remote
  trigger:
  - platform: time
    at: '23:01:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.shed_xmas_lights_1
  mode: single
