- id: '1661425963315'
  alias: Extend HW by 1 hour
  description: Sets the hot water thermostat to 26C for a period of 60 mins so that
    bathroom towel rail gets hot.
  trigger:
  - platform: state
    entity_id:
    - input_button.extend_hw
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 34
    target:
      entity_id: climate.hot_water
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: climate.set_temperature
    data:
      temperature: 0
    target:
      entity_id: climate.hot_water
  mode: restart
