---
# Welcome to my Home Assistant configuration!
#
homeassistant:

  # Lets me customize individual entities
  #  customize: !include_dir_merge_named ../customizations/entities

  # Lets me custimize all entities in a domain
  #customize_domain: !include_dir_merge_named ../customizations/domains

  # Lets me custimize entities based on a matching pattern
  #customize_glob: !include_dir_merge_named ../customizations/globs

  # All complex integrations are contained in packages
  packages: !include_dir_named packages
  
  # Use totp Multi-Factor Authentication (MFA)
  auth_mfa_modules:
    - type: totp

# Simple integrations are retained in here.

# Get a warning of any impending breaking changes
# https://github.com/custom-components/breaking_changes
#
breaking_changes:
  name: Potential Breaking changes
  scan_interval: 60

# Recorder
#
recorder:
  db_url: mysql://homeassistant:IsThisAStrongPassword?@core-mariadb/homeassistant?charset=utf8

# The config component enables a set of additional capabilities to manage and
#  # configure certain parts of Home Assistant straight from the frontend.
#
# https://www.home-assistant.io/components/config/
#

# Climate control

climate:
  - platform: zwave

config:

# Discover new devices
# https://www.home-assistant.io/integrations/discovery/
#
discovery:

# Home Assistant Community Store
# https://custom-components.github.io/hacs/

hacs:
  token: !secret hacs_token

# This enables the Hass.io panel in the Home Assistant frontend
hassio:

history:

# The Home Assistant for iOS app offers a companion app for iOS which
# is deeply integrated into both Home Assistant and iOS.
#
# https://www.home-assistant.io/components/ios/
# https://www.home-assistant.io/docs/ecosystem/ios/
#


ios:

# The logbook component provides a different perspective on the history of
# your house by showing all the changes that happened to your house in
# reverse chronological order.
#
# https://www.home-assistant.io/components/logbook/
#
logbook:

# Logger

logger:
  default: error
#  logs:
#    homeassistant.components.zwave: debug

# Lovelace UI
# https://www.home-assistant.io/lovelace/
# https://www.home-assistant.io/lovelace/yaml-mode/
#lovelace:
#    mode: yaml

# Google Map
# https://www.home-assistant.io/components/map/
map:

#
# The Mobile App component allows Home Assistant mobile apps to easily
# integrate with Home Assistant.
#
# https://www.home-assistant.io/components/mobile_app/
#
mobile_app:

# Moon sensor
# https://www.home-assistant.io/components/moon/

sensor:
  - platform: moon

# MQTT
# https://www.home-assistant.io/docs/mqtt/

    #mqtt:
    #  broker: mqtt.agdon.net
    #  username: !secret mqtt_username
    #  password: !secret mqtt_password
    #  client_id: hassio
    #  discovery: true

# The notify component allows us to send messages using Pushover
#
# https://www.home-assistant.io/integrations/pushover/
#
notify:
  - name: Pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: Pushover_Door
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_door_user_key

# rfxtrx
#
# https://www.home-assistant.io/integrations/rfxtrx/
#
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETXVE-if00-port0


# The speedtestdotnet integration uses the Speedtest.net
# web service to measure network bandwidth performance.
#
# https://www.home-assistant.io/components/speedtestdotnet/
#
speedtestdotnet:
  scan_interval:
    minutes: 15

# Sun
sun:
  elevation: !secret zone_home_elevation

# The System Health component provides an API to offer information
# on the system and its components.
#
# https://www.home-assistant.io/components/system_health/
#
system_health:

# Z-Wave integrations
#
# https://www.home-assistant.io/integrations/zwave
#
#zwave:
#  usb_path: /dev/serial/by-id/usb-0658_0200-if00
#  polling_interval: 60000
#  debug: true
