---
# Welcome to my Home Assistant configuration!
#
homeassistant:

  # All complex integrations are contained in packages
  packages: !include_dir_named packages

  # Use totp Multi-Factor Authentication (MFA)
  auth_mfa_modules:
    - type: totp

  # Allow local users in without a password
  #      auth_providers:
  #      - type: homeassistant
  #      - type: trusted_networks
  #        trusted_networks:
  #          - 172.29.12.0/24

# Simple integrations are retained in here.

# Get a warning of any impending breaking changes
# https://github.com/custom-components/breaking_changes
#
breaking_changes:
  name: Potential Breaking changes
  scan_interval: 60


# Recorder
# Store data in MariaDB instead of HA's SQLite database
# to get better performance
#
#recorder:
#  db_url: mysql://homeassistant:IsThisAStrongPassword?@core-mariadb/homeassistant?charset=utf8

# The config component enables a set of additional capabilities to manage and
#  # configure certain parts of Home Assistant straight from the frontend.
#
# https://www.home-assistant.io/components/config/
#
config:

# Discover new devices
# https://www.home-assistant.io/integrations/discovery/
#
discovery:

# This enables the Hass.io panel in the Home Assistant frontend
#
hassio:


# This tells HA to keep a history of the data
#
history:

# IOS
#ios:

# The logbook component provides a different perspective on the history of
# your house by showing all the changes that happened to your house in
# reverse chronological order.
#
# https://www.home-assistant.io/components/logbook/
#
logbook:

# Logger
# Control what gets logged in HA (to keep the noise level down)
#
logger:
  default: warning
  #  logs:
    #homeassistant.components.ozw: debug
    #homeassistant.components.rfxtrx: debug
    #homeassistant.components.mqtt: debug

# Lovelace UI
# https://www.home-assistant.io/lovelace/
# https://www.home-assistant.io/lovelace/yaml-mode/
#lovelace:
#    mode: yaml

# Google Map
# https://www.home-assistant.io/components/map/
map:

# Moon sensor
# https://www.home-assistant.io/components/moon/
#
sensor:
  - platform: moon


# MQTT
mqtt:
  broker: mqtt.agdon.net
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

# The notify component allows us to send messages using Pushover
# https://www.home-assistant.io/integrations/pushover/
#
notify:
  - name: Pushover_Gareth
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key
  - name: Pushover_Door
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_door_user_key
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#Home_Assistant'



# rfxtrx
#
# https://www.home-assistant.io/integrations/rfxtrx/
#
#rfxtrx:
#  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETXVE-if00-port0
#  debug: false

# Sun
sun:
  elevation: !secret zone_home_elevation

# The System Health component provides an API to offer information
# on the system and its components.
#
# https://www.home-assistant.io/components/system_health/
#
system_health:

zeroconf:
