# Main Configuration

# Main Settings
# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
    name: Howell Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: !secret home_elevation
    unit_system: metric
    temperature_unit: C
    time_zone: Europe/London

    auth_providers:
        - type: homeassistant

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: mqtt.agdon.net

# configuration.yaml entry
hello_mqtt:
  topic: some_mqtt/topic/here
