---
automation: !include automations.yaml

# Simple integrations are retained in here.

# The config component enables a set of additional capabilities to manage and
#  # configure certain parts of Home Assistant straight from the frontend.
#
# https://www.home-assistant.io/components/config/
#
config:

default_config:

# Energy Management
# https://www.home-assistant.io/docs/energy
#
energy:

# FFMPEG support for cameras
#
ffmpeg:

# Configures the official Home Assistant frontend.
#
# https://www.home-assistant.io/components/frontend/
#
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

  # We can define additional/custom themes for the frontend here.
  themes: !include_dir_merge_named themes

# This enables the Hass.io panel in the Home Assistant frontend
#
hassio:

# This tells HA to keep a history of the data
#
history:

homeassistant:
  # Use totp Multi-Factor Authentication (MFA)
  auth_mfa_modules:
    - type: totp

  # Load customizations
  customize: !include customizations.yaml

  # All complex integrations are contained in packages
  packages: !include_dir_named packages

# The logbook component provides a different perspective on the history of
# your house by showing all the changes that happened to your house in
# reverse chronological order.
#
# https://www.home-assistant.io/components/logbook/
#
logbook:

# Logger
# Control what gets logged in HA (to keep the noise level down)
#
logger:
  default: warning
  #logs:
  #homeassistant.components.alexa: debug
  #homeassistant.components.ozw: debug
  #homeassistant.components.rfxtrx: debug
  #homeassistant.components.mqtt: debug

# Lovelace
lovelace:
  mode: storage

# Media source
media_source:

# My Configuration
# https://www.home-assistant.io/integrations/my/
#
my:

recorder:
  db_url: mysql://homeassistant:D86pmj@core-mariadb/homeassistant?charset=utf8mb4
  purge_keep_days: 90

scene: !include scenes.yaml

script: !include scripts.yaml

# Sun
sun:

# The System Health component provides an API to offer information
# on the system and its components.
#
# https://www.home-assistant.io/components/system_health/
#
system_health:

tapo:
  discovery: true

# Text to speech
tts:
  - platform: google_translate

zeroconf:
