---
# Welcome to my Home Assistant configuration!
#
homeassistant:

  # All complex integrations are contained in packages
  packages: !include_dir_named packages

  # Use totp Multi-Factor Authentication (MFA)
  auth_mfa_modules:
    - type: totp


# Simple integrations are retained in here.

# The config component enables a set of additional capabilities to manage and
#  # configure certain parts of Home Assistant straight from the frontend.
#
# https://www.home-assistant.io/components/config/
#
config:

# Discover new devices
# https://www.home-assistant.io/integrations/discovery/
#
discovery:

# This enables the Hass.io panel in the Home Assistant frontend
#
hassio:


# This tells HA to keep a history of the data
#
history:

# IOS
#ios:

# The logbook component provides a different perspective on the history of
# your house by showing all the changes that happened to your house in
# reverse chronological order.
#
# https://www.home-assistant.io/components/logbook/
#
logbook:

# Logger
# Control what gets logged in HA (to keep the noise level down)
#
logger:
  default: warning
  #  logs:
    #homeassistant.components.ozw: debug
    #homeassistant.components.rfxtrx: debug
    #homeassistant.components.mqtt: debug

# Google Map
# https://www.home-assistant.io/components/map/
map:

# Moon sensor
# https://www.home-assistant.io/components/moon/
#
sensor:
  - platform: moon

# Sun
sun:
  elevation: !secret zone_home_elevation

# The System Health component provides an API to offer information
# on the system and its components.
#
# https://www.home-assistant.io/components/system_health/
#
system_health:

zeroconf:
