---
# Welcome to my Home Assistant configuration!
#
# The layour has been heavily based on that used by @frenk
# See https://github.com/frenck/home-assistant-config for more info
#
# My system is very modular and very differently structured
# compared to other configurations you'll find online.
#
# Basically, each file in the repository does 1 (one, uno, eins)
# thing only! Click through it, you'll get it pretty fast.
#
# The configuration.yaml is only used to bootstrap the system.
#
homeassistant:
  name: home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  time_zone: Europe/London
  unit_system: metric

  # Load packages
  packages: !include_dir_named integrations
