---
# When it gets dark outside
#
alias: living_room_sunset
# Lights on 30 minutes before sunset
trigger:
  - platform: sun
    event: sunset
    offset: '-00:15:00'
action:
  service: switch.turn_on
  entity_id: switch.living_room_lights
