alias: 'transform DZ temp'
trigger:
  - platform: mqtt
    topic: 'domoticz/out'
condition:
  condition: template
  value_template: '{{ trigger.payload_json.dtype == "Temp" }}'
action:
  - service: mqtt.publish
    data_template:
      topic: 'home/sensor/{{ trigger.payload_json.idx }}/temp'
      payload_template: '{{ trigger.payload_json.svalue1 }}'
