alias: "transform DZ switch output"
trigger:
  - platform: mqtt
    topic: 'home/switch/+/power'
action:
  - service: mqtt.publish
    data_template:
      topic: 'domoticz/in'
      payload_template: '{"command": "switchlight", "idx": {{ trigger.topic.split("/")[-2] }}, "switchcmd": "{{ trigger.payload }}" }'
      
