blueprint:
  name: Reboot HA host
  description: Automated weekly reboot of the entire Home Asistant OS host by Chef
    de IT
  author: Chef de IT
  domain: automation
  input:
    reboot_day:
      name: Reboot Day of Week
      description: Pick the best day to reboot, e.g. Tuesday
      default: tue
      selector:
        select:
          options:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
          custom_value: false
          multiple: false
    reboot_time:
      name: Reboot time of day
      description: Pick the least busy time for reboot, e.g. 4am
      default: 04:00:00
      selector:
        time: {}
  source_url: https://gist.github.com/Chef-de-IT/2a4cdb7a3739e121daac76df3e30e780
condition:
- condition: time
  before: 00:00:00
  after: 00:00:00
  weekday:
  - !input reboot_day
trigger:
- platform: time
  at: !input reboot_time
action:
- service: hassio.host_reboot
  data: {}
mode: single
