alias: set_house_vacant
trigger:
  - platform: state
    entity_id: device_tracker.life360_gareth, device_tracker.life360_varina
    to: 'not_home'
    for: "01:00:00"
  
action:
  service: input_boolean.turn_on
  entity_id: house_vacant
