esphome:
  name: sg-230

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_transport_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.30.81
    gateway: 192.168.30.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sg-230 Fallback Hotspot"
    password: !secret ap_password

captive_portal:

switch:
  # SG-230 Power switch
  - platform: gpio
    pin: D3
    name: "SG-230 Power"
    id: sg_230_power

  - platform: gpio
    pin: D4
    name: "SG-230 Tune"
    id: sg_230_tune
    interlock: &sg230_interlocks [sg_230_tune, sg_230_reset]

  - platform: gpio
    pin: D5
    name: "SG-230 Reset"
    id: sg_230_reset
    interlock: *sg230_interlocks
    

# 
binary_sensor:
  - platform: gpio
    pin: D4
    device_class: lock
    name: "SG-230 Tuned"
    id: sg230_tuned
