
influxdb:
  include:
    entities:
      - sensor.rad1_battery_level
      - sensor.rad2_battery_level
      - sensor.rad3_battery_level
      - sensor.rad4_battery_level
      - sensor.rad5_battery_level
      - sensor.shack_thermostat_battery_level

group:
  rad_batteries:
    entities:
      - sensor.rad1_battery_level
      - sensor.rad2_battery_level
      - sensor.rad3_battery_level
      - sensor.rad4_battery_level
      - sensor.rad5_battery_level
  thermostat_batteries:
    entities:
      - sensor.shack_thermostat_battery_level
   
binary_sensor:
  - platform: template
    sensors:
      low_battery_alarm:
        friendly_name: "Low Batteries"
        entity_id: sensor.time
        value_template: >-
          {% set entities = expand('group.batteries') %}
          {% for x in entities %}
            {% if states(x)|int < 30 %}
              {% set y = True %}
            {% endif %}
          {% endfor %}
          {{ y }}

  - platform: template
    sensors:
       master_alarm:
         friendly_name: "Master Alarm"
         entity_id: sensor.master_alarm
         value_template: >
           {{ states('low_battery_alarm') }}

alert:
  master_alarm:
    name: Master Alarm Sounding
    done_message: Master Alarm condition has been resolved
    entity_id: binary_sensor.master_alarm
    state: True
    repeat: 120
    can_acknowledge: True
    notifiers:
      notify.gareth


