---
alert:
  low_battery_devices:
    name: Some devices have low battery
    entity_id: binary_sensor.some_devices_have_low_battery
    title: "{{ states('sensor.devices_with_low_battery') }} devices have low battery"
    message: "Some devices need a battery change"
    state: "on"
    can_acknowledge: true
    repeat: 2880
    notifiers:
      - pushover_gareth

binary_sensor:
  - platform: threshold
    entity_id: sensor.devices_with_low_battery
    name: Some devices have low battery
    upper: 0.5

  # Raise a Master Alarm if a battery has a low battery
  - platform: template
    sensors:
      master_alarm:
        friendly_name: "Master Alarm"
        value_template: >-
          {{
              states('binary_sensor.some_devices_have_low_battery')
          }}
        delay_on: 0:05:00

sensor:
  # Filtered Battery levels
  - platform: filter
    name: "filtered Shed Battery"
    entity_id: sensor.shed_battery
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 1

  - platform: filter
    name: "filtered Bedroom1 Battery"
    entity_id: sensor.bedroom1_battery
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 1

  - platform: filter
    name: "filtered Livingroom Battery"
    entity_id: sensor.livingroom_battery
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 1

  - platform: filter
    name: "filtered Bedroom2 Battery"
    entity_id: sensor.bedroom2_battery
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 1

  - platform: filter
    name: "filtered Shack Battery"
    entity_id: sensor.shack_battery
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 1

  - platform: filter
    name: "filtered EmonTx1 Battery"
    entity_id: sensor.emontx1_battery
    filters:
      - filter: lowpass
        time_constant: 10
        precision: 1

  # Low batteries
  # The number of devices with 'Low Battery' binary_sensor 'on'
  - platform: template
    sensors:
      devices_with_low_battery_sensor_active:
        friendly_name: "Devices with low battery sensor active"
        unit_of_measurement: devices
        value_template: >-
          {{ states.binary_sensor
            | selectattr('attributes.device_class', 'eq', 'battery')
            | map(attribute='state')
            | select('eq', 'on')
            | list | count
          }}
        icon_template: >-
          {% if is_state('binary_sensor.devices_with_low_battery_sensor_active', '0') %}
            mdi:check-circle
          {% else %}
            mdi:battery-alert
          {% endif %}

  # The number of devices whose battery charge is below 10%
  - platform: template
    sensors:
      devices_with_low_battery_charge:
        friendly_name: "Devices with low battery charge"
        unit_of_measurement: devices
        value_template: >-
          {{ states.sensor
            | selectattr('attributes.device_class', 'eq', 'battery')
            | selectattr('attributes.unit_of_measurement', 'eq', '%' )
            | rejectattr('attributes.state_class', 'eq', 'measurement')
            | map(attribute='state')
            | reject('in', ['unknown', 'unavailable', 'Ok'])
            | map('int', -1) | select('le', 10)
            | list | count
          }}
        icon_template: >-
          {% if is_state('sensor.devices_with_low_battery_charge', '0') %}
            mdi:check-circle
          {% else %}
            mdi:battery-alert
          {% endif %}

  # The number of devices whose battery voltage is below 1.6V
  - platform: template
    sensors:
      devices_with_low_battery_voltage:
        friendly_name: "Devices with low battery voltage"
        unit_of_measurement: devices
        value_template: >-
          {{ states.sensor
            | selectattr('attributes.device_class', 'eq', 'voltage')
            | selectattr('attributes.unit_of_measurement', 'eq', 'V' )
            | selectattr('attributes.type', 'eq', 'filtered')
            | map(attribute='state')
            | reject('in', ['unknown', 'unavailable', 'Ok'])
            | map('float', -1) | select('le', 1.6)
            | list | count
          }}
        icon_template: >-
          {% if is_state('sensor.devices_with_low_battery_voltage', '0') %}
            mdi:check-circle
          {% else %}
            mdi:battery-alert
          {% endif %}

  # The number of devices which have a low battery state
  - platform: template
    sensors:
      devices_with_low_battery:
        friendly_name: "Devices with low battery"
        unit_of_measurement: devices
        value_template: >-
          {{
            states('sensor.devices_with_low_battery_charge') | int +
            states('sensor.devices_with_low_battery_voltage') | int +
            states('sensor.devices_with_low_battery_sensor_active') | int
          }}
        icon_template: >-
          {% if is_state('sensor.devices_with_low_battery', '0') %}
            mdi:check-circle
          {% else %}
            mdi:battery-alert
          {% endif %}

mqtt:
  sensor:
    - name: "Shed Battery"
      state_topic: "emon/emonth4/battery"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Bedroom1 Battery"
      state_topic: "emon/emonth5/battery"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Livingroom Battery"
      state_topic: "emon/emonth6/battery"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Bedroom2 Battery"
      state_topic: "emon/emonth7/battery"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Shack Battery"
      state_topic: "emon/emonth8/battery"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "EmonTx1 Battery"
      state_topic: "emon/emontx1/battery"
      unit_of_measurement: "V"
      device_class: voltage
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300
