sensor:
  - platform: emoncms
    api_key: !secret opencms_api_key
    url: http://emonpi.agdon.net
    id: 2
    unit_of_measurement: "V"
    sensor_names:
      27: "Livingroom Battery"
      28: "Bedroom1 Battery"   
      35: "Bedroom2 Battery"
      39: "Shack Battery"

  - platform: template
    sensors:
      low_batteries:
        value_template: >-
          {% set sep1 = joiner(", ") %}
          {% set sep2 = joiner(" (") %}
          {% set sep3 = joiner(")") %}
          {% set res = "*" %}
          {% for battery in (states | selectattr('attributes.device_class', 'eq', 'battery')) %}
            {% set charge = battery.state| int %}
            {% if  charge > 0 and charge < 20 %}
              {{ res + sep1() + battery.entity_id + sep2() + battery.state + sep3() }} 
              {% endif %}
            {% endfor %}
          {{ res }}

binary_sensor:
    - platform: template
      sensors:
        low_battery_alarm:
          friendly_name: "Low Battery Alarm"
          #entity_id: sensor.time
          value_template: >-
            {% if not states('sensor.low_batteries') == "*" %}
              {% set y = True %}
              {% endif %}
            {{ y }}

    - platform: template
      sensors:
        master_alarm:
          friendly_name: "Master Alarm"
          value_template: >
            {% set res = False %}
            {% if states('binary_sensor.low_battery_alarm') == "on" %}
              {% set res = True %}
              {% endif %}
            {{ res }}

alert:
    master_alarm:
        name: Master Alarm Sounding
        done_message: Master Alarm condition has been resolved
        entity_id: binary_sensor.master_alarm
        state: 'on'
        repeat: 120
        can_acknowledge: True
        notifiers:
          - pushover_gareth
          - slack
