---
homeassistant:
  customize:

    sensor.shack_environment:
      hidden: true

    sensor.openweathermap_temperature:
      friendly_name: "Ext Temp"
    sensor.openweathermap_humidity:
      friendly_name: "Ext Humidity"
    sensor.external_eemperature_2:
      friendly_name: "External Temperature"

    binary_sensor.cold_outside:
      device_class: cold
    binary_sensor.freezing_outside:
      device_class: cold


sensor:
# Temperatures
  - platform: mqtt
    state_topic: 'emon/emonth4/temperature'
    name: 'Shed Temperature'
    unit_of_measurement: '°C'
    device_class: temperature
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth5/temperature"
    name: "Bedroom1 Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth6/temperature"
    name: "Livingroom Temperature"
    device_class: temperature
    value_template: '{{ value | float | round(1) }}'
    unit_of_measurement: "°C"
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth6/external temperature"
    name: "External Temperature_2"
    unit_of_measurement: "°C"
    device_class: temperature
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth7/temperature"
    name: "Bedroom2 Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth8/temperature"
    name: "Shack Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

# Humidity
  - platform: mqtt
    state_topic: "emon/emonth5/humidity"
    name: "Bedroom1 Humidity"
    unit_of_measurement: "%"
   
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300 
    
  - platform: mqtt
    state_topic: "emon/emonth6/humidity"
    name: "Livingroom Humidity"
    unit_of_measurement: "%"
    
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth7/humidity"
    name: "Bedroom2 Humidity"
    unit_of_measurement: "%"
    
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

  - platform: mqtt
    state_topic: "emon/emonth8/humidity"
    name: "Shack Humidity"
    unit_of_measurement: "%"
   
    value_template: '{{ value | float | round(1) }}'
    expire_after: 300

# Indicators that external temps are low
binary_sensor:
  - platform: template
    sensors:
      cold_outside:
        friendly_name: "Low Temp"
        #entity_id: sensor.external_temperature_2
        value_template: >-
          {% if states('sensor.external_temperature_2') | float  < 5.0 %}
          true
          {% else %}
          false
          {% endif %}
      freezing_outside:
        friendly_name: "Freezing!"
        #entity_id: sensor.external_temperature_2
        value_template: >-
          {% if states('sensor.external_temperature_2') | float  < 0.3 %}
          true
          {% else %}
          false
          {% endif %}
