---
homeassistant:
  customize:
    sensor.shack_environment:
      hidden: true

    sensor.openweathermap_temperature:
      friendly_name: "Ext Temp"
    sensor.openweathermap_humidity:
      friendly_name: "Ext Humidity"
    sensor.external_Temperature_2:
      friendly_name: "External Temperature"

    binary_sensor.cold_outside:
      device_class: cold
    binary_sensor.freezing_outside:
      device_class: cold

mqtt:
  sensor:
    # Temperatures
    - name: "Shed Temperature"
      state_topic: "emon/emonth4/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Bedroom1 Temperature"
      state_topic: "emon/emonth5/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Livingroom Temperature"
      state_topic: "emon/emonth6/temperature"
      device_class: temperature
      value_template: "{{ value | float | round(1) }}"
      unit_of_measurement: "°C"
      expire_after: 300

    - name: "External Temperature_2"
      state_topic: "emon/emonth6/external temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Bedroom2 Temperature"
      state_topic: "emon/emonth7/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Shack Temperature"
      state_topic: "emon/emonth8/temperature"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    # Humidity
    - name: "Bedroom1 Humidity"
      state_topic: "emon/emonth5/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Livingroom Humidity"
      state_topic: "emon/emonth6/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Bedroom2 Humidity"
      state_topic: "emon/emonth7/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Shack Humidity"
      state_topic: "emon/emonth8/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

    - name: "Shed Humidity"
      state_topic: "emon/emonth4/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value | float | round(1) }}"
      expire_after: 300

# Indicators that external temps are low
template:
  - binary_sensor:
      - name: cold_outside
        #friendly_name: "Low Temp"
        #entity_id: sensor.external_temperature_2
        state: >
          {% if states('sensor.external_temperature_2') | float  < 5.0 %}
          true
          {% else %}
          false
          {% endif %}
        availability: "{{ states('sensor.external_temperature_2') | float >= -30.0 }}"
      - name: freezing_outside
        #friendly_name: "Freezing!"
        #entity_id: sensor.external_temperature_2
        state: >
          {% if states('sensor.external_temperature_2') | float  < 0.3 %}
          true
          {% else %}
          false
          {% endif %}
        availability: "{{ states('sensor.external_temperature_2') | float >= -30.0 }}"
#binary_sensor:
##  - platform: template
#    sensors:
#      cold_outside:
#        friendly_name: "Low Temp"
#        #entity_id: sensor.external_temperature_2
#        value_template: >-
#          {% if states('sensor.external_temperature_2') | float  < 5.0 %}
#          true
#          {% else %}
#          false
#          {% endif %}
#        availability_template: "{{ states('sensor.external_temperature_2') | float >= -30.0) }}"
#      freezing_outside:
#        friendly_name: "Freezing!"
#        #entity_id: sensor.external_temperature_2
#        value_template: >-
#          {% if states('sensor.external_temperature_2') | float  < 0.3 %}
#          true
#          {% else %}
#          false
#          {% endif %}
#        availability_template: "{{ states('sensor.external_temperature_2') | float >= -30.0) }}"
