---
homeassistant:
  customize:
    sensor.shack_environment:
      hidden: true

sensor:
  - platform: mqtt
    state_topic: 'home/sensor/499/hum'
    name: 'External Humidity'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: 'home/sensor/499/temp'
    name: 'External Temperature'
    unit_of_measurement: '°C'
  - platform: mqtt
    state_topic: 'home/sensor/509/hum'
    name: 'Shack Humidity'
    unit_of_measurement: '%'
  - platform: mqtt
    state_topic: 'tel/19c/shed/temp'
    name: 'Shed Temperature'
    unit_of_measurement: '°C'
    device_class: temperature
    value_template: '{{ value_json.sValue }}'
  - platform: rfxtrx
    automatic_add: true
    #devices:
    #  "a520900d30002a61a0279":
    #    name: Shack Environment
    #    data_type:
    #      - Temperature
    #      - Humidity

  - platform: template
    sensors:
      shack_temp:
        friendly_name: "Shack Temp"
        entity_id: sensor.shack_environment_temperature # react only to this entity's changes
        unit_of_measurement: "C"
        value_template:
          "{{ states('sensor.shack_environment_temperature')| float - 41.0 }}"

  - platform: template
    sensors:
      shack_humidity:
        friendly_name: "Shack Humidity"
        entity_id: sensor.shack_environment_humidity # react only to this entity's changes
        unit_of_measurement: "%"
        value_template:
          "{{ states('sensor.shack_environment_humidity')| float }}"

automation:
  - alias: 'Turn on Shed Fan'
    description: 'Turn on Shed Fan when temp goes above 22C'
    trigger:
      - above: 22
        entity_id: sensor.shed_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: switch.shed_fan
        state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.shed_fan

  - alias: 'Turn off Shed Fan'
    description: 'Turn off Shed Fan when temp drops below 20C'
    trigger:
      - below: 20
        entity_id: sensor.shed_temperature
        platform: numeric_state
    condition:
      - condition: state
        entity_id: switch.shed_fan
        state: 'on'
    action:
      - service: switch.turn_off
        entity_id: switch.shed_fan
        
