---
homeassistant:
  customize:
    switch.central_heating_boiler_ch:
      friendly_name: "CH Boiler"
    input_boolean.livingroom_heat_demand:
      device_class: heat
    binary_sensor:we_need_heat:
      device_class: heat
    sensor.shack_temperature:
      friendly_name: "Shack Temperature"

mqtt:
  switch:
    # Shelly switch controlling CH side of boiler
    - name: Central Heating Boiler - CH
      unique_id: central_heating_boiler_ch
      payload_on: "on"
      payload_off: "off"
      qos: 1
      state_topic: shellies/shellyswitch25-76CD68/relay/1
      command_topic: shellies/shellyswitch25-76CD68/relay/1/command
      json_attributes_topic: shellies/shellyswitch25-76CD68/info

# Shed Thermostats
# Use generic_thermostat to keep temp between 6 and 24
climate:
  - platform: generic_thermostat
    name: "Shed Thermostat Low"
    heater: switch.shed_heater
    ac_mode: false
    target_sensor: sensor.shed_temperature
    min_temp: 4
    max_temp: 15
    target_temp: 7
    initial_hvac_mode: "heat"
    precision: 0.5

  - platform: generic_thermostat
    name: "Shed Thermostat High"
    heater: switch.shed_fan
    ac_mode: true
    target_sensor: sensor.shed_temperature
    min_temp: 4
    max_temp: 30
    target_temp: 22
    initial_hvac_mode: "cool"
    precision: 0.5

  # Shack Thermostat
  - platform: generic_thermostat
    name: "Shack Thermostat"
    heater: switch.shack_heater
    ac_mode: false
    target_sensor: sensor.shack_temperature
    min_temp: 0
    max_temp: 30
    target_temp: 4
    initial_hvac_mode: "heat"
    precision: 0.5

  # Hot Water thermostat - used to enable boiler in morning
  #  to warm towel rail even if rooms don't need heating
  - platform: generic_thermostat
    name: "Hot Water"
    heater: input_boolean.heated_towelrail_heat_demand
    ac_mode: false
    target_sensor: sensor.external_temperature_2
    min_temp: -10
    max_temp: 35
    target_temp: -10
    initial_hvac_mode: "heat"
    precision: 0.5

  # Room thermostats
  # Livingroom
  - platform: generic_thermostat
    name: "Livingroom Thermostat"
    heater: input_boolean.livingroom_heat_demand
    ac_mode: false
    target_sensor: sensor.livingroom_temperature
    min_temp: 4
    max_temp: 30
    #    hot_tolerance: -1.5
    target_temp: 6
    initial_hvac_mode: "heat"
    precision: 0.5

  # Bedroom 1
  - platform: generic_thermostat
    name: "Bedroom 1 Thermostat"
    heater: input_boolean.bedroom1_heat_demand
    ac_mode: false
    target_sensor: sensor.bedroom1_temperature
    min_temp: 4
    max_temp: 30
    target_temp: 6
    #    hot_tolerance: -1.5
    initial_hvac_mode: "heat"
    precision: 0.5

  # Bedroom 2
  - platform: generic_thermostat
    name: "Bedroom 2 Thermostat"
    heater: input_boolean.bedroom2_heat_demand
    ac_mode: false
    target_sensor: sensor.bedroom2_temperature
    min_temp: 4
    max_temp: 30
    target_temp: 6
    #    hot_tolerance: -1.5
    initial_hvac_mode: "heat"
    precision: 0.5

input_boolean:
  # Buttons to manipulate living room temps up and down
  living_room_temperature_up:
    name: "Living Room Temperature Up"
    initial: off
  living_room_temperature_down:
    name: "Living Room Temperature Down"
    initial: off

  # Switch to override central heating - reset at 00:01 each day
  central_heating_manual:
    name: "Central Heating on Manual"
    initial: off

  # Switch to disable set-back when house is vacant
  setback_disable:
    name: "Disable vacant house setback"
    initial: off

  # Virtual switch to simulate bedtime at any time
  simulate_bedtime:
    name: "Simulate Bedtime"
    initial: off

  # Virtual switches for rooms demanding heat
  livingroom_heat_demand:
    name: "Living Room Heating"
    initial: off
  bedroom1_heat_demand:
    name: "Bedroom 1 Heating"
    initial: off
  bedroom2_heat_demand:
    name: "Bedroom 2 Heating"
    initial: off
  heated_towelrail_heat_demand:
    name: "Heated Towel Rail Heating"
    initial: off

binary_sensor:
  # Overall indicator that we need heat
  - platform: template
    sensors:
      we_need_heat:
        friendly_name: "We need heat"
        #  entity_id:
        #    - input_boolean.livingroom_heat_demand
        #    - input_boolean.bedroom1_heat_demand
        #    - input_boolean.bedroom2_heat_demand
        #    - input_boolean.central_heating_manual
        #    - input_boolean.heated_towelrail_heat_demand
        value_template: >-
          {% if states('input_boolean.livingroom_heat_demand') == 'on' or
            states('input_boolean.bedroom1_heat_demand') == 'on' or
            states('input_boolean.bedroom2_heat_demand') == 'on' or
            states('input_boolean.central_heating_manual') == 'on' or
            states('input_boolean.heated_towelrail_heat_demand') == 'on'
          %}
            true
          {% else %}
            false
          {% endif %}
