#
# tracks whether the house is occupied or not
#

input_boolean:
  house_vacant:
    name: "House Vacant?"
    initial: off
    icon: mdi:home
  #home_tomorrow:
  #  name: Home Tomorrow?
  #  initial: off
  #  icon: mdi:home
  visitors:
    name: Have we visitors?
    initial: off
    icon: mdi:human-male-female

input_select:
  #
  # input_select to indicate that we are home
  #
  house_mode:
    name: House Mode?
    options:
      - Home
      - Away
    icon: mdi:thermostat

  # input select to indicate which season we are in.
  # Used by Schedy to set climate controls
  #
  season:
    name: Season?
    options:
      - Winter
      - Spring
      - Summer

scene:
  - name: "Home"
    entities:
      input_select.house_mode: "Home"

  - name: "Away"
    entities:
      input_select.house_mode: "Away"

sensor:
  # The time and date (time_date) sensor platform.
  # Has the time in various formats, the date, or both.
  #
  # This is usefull for displaying and automation purposes.
  #
  # https://www.home-assistant.io/components/time_date/
  #
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      #- 'date_time_iso'
      #- 'time_date'
      #- 'time_utc'
      #- 'beat'
