#
# tracks whether the house is occupied or not
#

input_boolean:
  house_vacant:
    name: "House Vacant?"
    initial: off
    icon: mdi:home
  home_tomorrow:
    name: Home Tomorrow?
    initial: off
    icon: mdi:home
  visitors:
    name: Have we visitors?
    initial: off
    icon: mdi:human-male-female

input_select:
  #
  # input_select to indicate that we are home tomorrow
  # This is used to set the state of input_select.heating_mode tomorrow,
  # otherwise, heating_mode will be reset back to "normal" tomorrow.
  #
  house_mode:
    name: House Mode?
    options:
      - Home - Normal Day
      - Home - Home Day
      - Away
    icon: mdi:thermostat

  # input select to indicate which season we are in.
  # Used by Schedy to set climate controls
  #
  season:
    name: Season?
    options:
      - Winter
      - Spring
      - Summer

sensor:
  # The time and date (time_date) sensor platform.
  # Has the time in various formats, the date, or both.
  #
  # This is usefull for displaying and automation purposes.
  #
  # https://www.home-assistant.io/components/time_date/
  #
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      #- 'date_time_iso'
      #- 'time_date'
      #- 'time_utc'
      #- 'beat'

automation:
  - alias: house vacant
    description: ""
    trigger:
      - platform: state
        entity_id: group.all_people
        from: home
        to: not_home
        for: "00:01:00"
    condition: []
    action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.house_vacant
    mode: single

  - alias: house not vacant
    description: ""
    trigger:
      - platform: state
        entity_id: group.all_people
        from: not_home
        to: home
        for: "00:01:00"
    condition: []
    action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.house_vacant
    mode: single
