group:
  all_lights:
    name: All House Lights
    entities:
      - switch.livingroom_standard_lamps

  main_livingroom_lights:
    name: Living Room Lights
    entities:
      - switch.livingroom_standard_lamps

scene:
  - name: Normal Evening
    entities: 
      switch.livingroom_standard_lamps: on

  - name: Christmas Evening
    entities:
      switch.livingroom_standard_lamps: on
      switch.shack_external_lights: on
      switch.shed_heater: on

  - name: Goodnight
    entities:
      switch.livingroom_standard_lamps: off
      switch.shack_external_lights: off
      switch.shed_heater: off

automation:
  # When it gets dark outside
  #
  - alias: Christmas lights at sunset
  # Christmas Lights on 30 minutes before sunset if house is not vacant
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.house_mode
          state: 'Home - Normal Day'
        - condition: state
          entity_id: input_select.house_mode
          state: 'Home - Normal Day'
    action:
      service: scene.turn_on
      entity_id: scene.christmas_evening

  - alias: Normal lights at sunset
  # Normal Lights on 30 minutes before sunset if house is vacant
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    condition:
      - condition: state
        entity_id: input_select.house_mode
        state: 'Away'
    action:
      service: scene.turn_on
      entity_id: scene.normal_evening

  - alias: lights_out
    # Switch lights off at 11PM
    trigger:
      platform: time
      at: "23:00:00"
    action:
      service: scene.turn_on
      entity_id: scene.goodnight

  # Switch on living room lights if it is raining outside
  # From https://www.home-assistant.io/cookbook/automation_for_rainy_days/
  #
  - alias: 'Rainy Day'
    trigger:
      platform: state
      entity_id: sensor.dark_sky_precip_intensity
      to: 'rain'
    condition:
      - condition: state
        entity_id: device_tracker.life360_gareth
        state: 'home'
      - condition: time
        after: '14:00'
        before: '23:00'
    action:
      service: light.turn_on
      entity_id: group.living_room_lights
