group:
  evening_lights:
    name: Lights that come on automatically in the evening
    entities:
      - switch.livingroom_standard_lamps

scene:
  - name: Evening
    entities:
      group.evening_lights: on

  - name: Goodnight
    entities:
      group.evening_lights: off
      switch.central_heating_boiler_ch: off
      
automation:
  # When it gets dark outside
  #
  - alias: Lights on at sunset
  # Lights on 30 minutes before sunset if house is not vacant
    trigger:
      platform: sun
      event: sunset
      offset: '-00:30:00'
    action:
      service: scene.turn_on
      entity_id: scene.evening

  - alias: lights_out
    # Switch lights off at 11PM
    trigger:
      platform: time
      at: "23:00:00"
    action:
      service: scene.turn_on
      entity_id: scene.goodnight

  # Switch on living room lights if it is raining outside
  # From https://www.home-assistant.io/cookbook/automation_for_rainy_days/
  #
  - alias: 'Rainy Day'
    trigger:
      platform: state
      entity_id: sensor.dark_sky_precip_intensity
      to: 'rain'
    condition:
      - condition: state
        entity_id: device_tracker.life360_gareth
        state: 'home'
      - condition: time
        after: '14:00'
        before: '23:00'
    action:
      service: scene.turn_on
      entity_id: scene.evening
