
homeassistant:
  customize:
    device_tracker.varinas_iphone:
      friendly_name: Varina
    device_tracker.ghip7plus:
      friendly_name: Gareth

input_boolean:
  shack_occupied:
    name: "Shack Occupied"
    icon: mdi:house
