homeassistant:
  customize:
    device_tracker.v_iphone:
      friendly_name: Varina

    device_tracker.ghip7plus:
      friendly_name: Gareth

group:
  all_people:
    name: "All people needing to be tracked"
    entities:
      - device_tracker.ghipv7plus
      - device_tracker.v_iphone
