---
# rfxtrx
#
# https://www.home-assistant.io/integrations/rfxtrx/
#
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETXVE-if00-port0

sensor:
  platform: rfxtrx
  automatic_add: true
  devices:
    "07160063003d0150":
      name: doorbell
      data_type: Sound
      fire_event: true #Because the state doesn't reset

automation:
  - alias: "Doorbell pressed"
    trigger:
      - platform: event
        event_type: signal_received
        event_data:
          entity_id: sensor.doorbell_sound
    action:
      - service: notify.pushover
        data:
          message: "Ding, Dong! Front Doorbell"
