---
# rfxtrx
#
# https://www.home-assistant.io/integrations/rfxtrx/
#
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETXVE-if00-port0

homeassistant:
  customize:
    sensor.shack_environment:
      friendly_name: Shack

sensor:
  platform: rfxtrx
  automatic_add: true
  devices:
    "07160018005c0170":
      name: doorbell
      data_type: Sound
      fire_event: true #Because the state doesn't reset

    "0a520902dd0002652b0159":
      name: Shack Environment
      data_type: 
        - Temperature
        - Humidity

automation:
  - alias: "Doorbell pressed"
    trigger:
      - platform: event
        event_type: signal_received
        event_data:
          entity_id: sensor.doorbell_sound
    action:
      - service: notify.pushover_door
        data:
          message: "Ding, Dong! Front Doorbell"
