---
# rfxtrx
#
# https://www.home-assistant.io/integrations/rfxtrx/
#
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1XETXVE-if00-port0

sensor:
  platform: rfxtrx
  automatic_add: false
  devices:
    07160062003d0150:
      name: Front Door
      data_type:
        - Sound

automation:
  - alias: "Doorbell pressed"
    trigger:
      - platform: event
        event_type: signal_received
        event_data: {"entity_id": "sensor.front_door_bell"}
    action:
      - service: notify.pushover
        data:
          message: "Ding, Dong!"
