
# Weather
# https://www.home-assistant.io/integrations/sensor.metoffice/
#
---
sensor:
  - platform: metoffice
    api_key: !secret metoffice_api_key
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - uv
      - visibility
      - visibility_distance
      - wind_speed
      - wind_direction
      - precipitation

  - platform: openweathermap
    api_key: !secret openweather_api_key
    monitored_conditions:
      - weather
      - temperature
      - humidity
      - wind_speed
      - wind_bearing
      - pressure
      - clouds
      - rain
      - snow
      - weather_code
        

weather:
  - platform: metoffice
    api_key: !secret metoffice_api_key

  - platform: openweathermap
    api_key: !secret openweather_api_key
