
# Weather
# https://www.home-assistant.io/integrations/sensor.metoffice/
#
---
sensor:
        #  - platform: metoffice
        #    api_key: !secret metoffice_api_key

  - platform: openweathermap
    api_key: !secret openweather_api_key

weather:
        #  - platform: metoffice

  - platform: openweathermap
